spring.application.name=ecomerce

# JWT
api.security.token.secret=4z6B8EbGaKgNjQnTqVtWvYx2z1C3E5H7McQfTjWnZr4u7x!A%D*G-KaPdSgVkYp

# CONFIGURAÇÃO DO DATASOURCE (H2 em Arquivo)
spring.datasource.url=jdbc:h2:file:./data/ecommercedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=admin@admin

# JPA / HIBERNATE
# 'update' mantém os dados; 'create' apaga tudo ao iniciar
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# CONSOLE H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Libera o acesso ao console se você usar Spring Security
spring.h2.console.settings.web-allow-others=true

